version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: manager-server
    restart: always
    environment:
      POSTGRES_USER: manager-server
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: manager-server
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
